### ISSUE TITLE
 Add short describtion to GitHub project 

### ISSUE THREAD

**Issue by jcfr** [SlicerProstate/SlicerZFrameRegistration#1]
This can be done clicking on Edit button on the top of [this](https://github.com/SlicerProstate/SlicerZFrameRegistration) page

**Comment by leochan2009** [comment]
@che85 
Could you add description for this project?
It seems like i don't have permission to edit the topic.(Edit button is not visible)
Add topic: 
This extension can be used for the registration between intra-procedural image frame of reference with the transperineal biopsy or cryoablation templates.

**Comment by leochan2009** [comment]
Solved
